### ISSUE TITLE
Arrow directions for East and West appear to be backwards

### ISSUE THREAD

**Issue by xenxero1** [Tre5et/simple-compass#4]
![image](https://github.com/Tre5et/simple-compass/assets/14264597/1cedc631-5527-4890-94f4-117a36cd6fc9)
East and west arrows appear backward, or at the very least incredibly unintuitive.

**Comment by Tre5et** [comment]
The arrows are meant to point north if you are looking directly in the cardinal direction that they are associated with. So the east arrow points left for example because north is to your left if you are looking east. 
If you don't like these arrows however, you can always turn on minimalist mode to completely get rid of them or make you own resourcepack to overwrite the sprites :)
